objects = exe
cfile = test.c
executable = execut
executecommand = ./$(executable)


PHONY: clean, $(objects)

$(objects): $(executable)
	@$(executecommand)

$(executable): $(cfile)
	@gcc -Wall $^ -o $@ 

clean:
	rm -f $(executable)
	rm -f *.o